### ISSUE TITLE
Questions about epoch

### ISSUE THREAD

**Issue by zp19990818** [suhwan-cho/TMO#3]
Hello, I'm sorry to bother you again.

In the project, max_epoch is set to 4000. Although the setting is large, the training and convergence are fast. But according to my past experience, isn't the epoch usually set between 100~300? I have set the epoch to 200 on other models, but the training is slower than yours, and they achieve a similar degree of accuracy.

So, I would like to ask what is the epoch here. Is it Iterations or some other parameter? I feel very confused. Could you give me some help?

**Comment by suhwan-cho** [comment]
Hi,

To use VOS and SOD samples simultaneously with a designated ratio, the number of training samples per epoch is explicitly set to certain values (128 VOS samples and 384 SOD samples). If you want to compare the training process of TMO and other methods, you need to calculate the number of iterations instead of the number of epochs.

**Comment by zp19990818** [comment]
Got it!

Thank you very much
